---
title: True Dhamma
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog

'
    feature_image: https://picsum.photos/2560/600?image=866
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/default-social-image.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
paginate: 10
paginate_path: blog/page:num
jekyll-mentions: 
twitter:
  username: 
author: 智宁居士
social:
  name: 
  links:
  - 
  - 
  - 
  - 
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
lang: zh-CN
logo: "/uploads/Dhamma_Wheel.svg.webp"
description: 世间成瘾与出世间觉悟,南传上座部,佛法,解脱,彼岸,涅槃,修行,实修,实证
url: https://true-dhamma.github.io
baseurl: 
repo: 
email: zhining@gmx.com
css_inline: true
favicons:
  '16': "/uploads/siteicon.png"
  '32': "/uploads/siteicon.png"
  '96': "/uploads/siteicon.png"
  '120': "/uploads/siteicon.png"
  '144': "/uploads/siteicon.png"
  '180': "/uploads/siteicon.png"
  '512': "/uploads/siteicon.png"
  '1024': "/uploads/siteicon.png"
navigation_header:
- title: 首页
  url: "/"
- title: 巴利圣典
  url: "/南传上座部佛教/2025/08/09/巴利圣典/"
- title: 文章
  url: "/categories/"
- title: 网盘
  url: https://download.true-dhamma.com/
- title: 搜索
  url: "/search/"
- title: 关于本站
  url: "/about/"
navigation_footer:
- title: Created by 智宁居士
  url: mailto:zhining@gmx.com
social_links:
  Twitter: 
  LinkedIn: 
  GitHub: 
  link: https://true-dhamma.com
  RSS: "/feed.xml"
sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
fonts:
  preconnect_urls:
  - https://fonts.gstatic.com
  font_urls:
  - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
