---
title: True Dhamma
timezone: Asia/Shanghai
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: 文章
    output: true
    feature_image: "/uploads/top_banner_blog.jpg"
defaults:
- scope:
    path: ''
  values:
    image: "/assets/default-social-image.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
paginate: 20
paginate_path: "/blog/page:num"
jekyll-mentions: 
twitter:
  username: 
author: 智宁居士
social:
  name: 
  links:
  - 
  - 
  - 
  - 
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
lang: zh-CN
logo: "/uploads/Dhamma_Wheel.svg.webp"
description: 世间成瘾与出世间觉悟，南传上座部佛法，实修实证，亲知实见，趋向涅槃，从无明中解脱
url: https://true-dhamma.github.io
baseurl: 
repo: 
email: zhining@gmx.com
css_inline: true
favicons:
  '16': "/uploads/siteicon.png"
  '32': "/uploads/siteicon.png"
  '96': "/uploads/siteicon.png"
  '120': "/uploads/siteicon.png"
  '144': "/uploads/siteicon.png"
  '180': "/uploads/siteicon.png"
  '512': "/uploads/siteicon.png"
  '1024': "/uploads/siteicon.png"
navigation_header:
- title: 首页
  url: "/"
- title: 成瘾
  url: "/addiction/"
- title: 文章
  url: "/blog/"
- title: 巴利圣典
  url: "/tipitaka/"
- title: 网盘
  url: https://download.true-dhamma.com/
- title: 搜索&提问
  url: "/search/"
- title: 关于本站
  url: "/about/"
navigation_footer:
- title: Created by 智宁居士
  url: mailto:zhining@gmx.com
social_links:
  Twitter: 
  LinkedIn: 
  GitHub: 
  link: https://true-dhamma.github.io
  RSS: "/feed.xml"
sharing_links:
  Twitter: ''
  facebook: ''
  Email: true
  UniversalShare: "#4CAF50"
fonts:
  preconnect_urls:
  - https://fonts.gstatic.com
  font_urls:
  - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
