---
title: True Dhamma
timezone: Asia/Shanghai
collections:
  buddhadhamma:
    title: Buddhadhamma (P.A.Payutto)
    output: true
    permalink: "/:collection/:name.html"
  posts:
    title: Posts
    output: true
  testbook:
    title: Testbook
    output: true
    permalink: "/:collection/:name.html"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    feature_image: "/uploads/top_banner_blog.jpg"
    toc: true
    aside: false
- scope:
    path: ''
    type: buddhadhamma
  values:
    layout: doc
    feature_image: "/uploads/top_banner_dhamma.jpg"
    toc: true
- scope:
    path: ''
    type: testbook
  values:
    layout: doc
- scope:
    path: ''
  values:
    seo_description_max_words: 20
url: https://true-dhamma.com
baseurl: ''
description: 世间成瘾与出世间觉悟，南传上座部佛法，实修实证，亲知实见，趋向涅槃，从无明中解脱。
encoding: utf-8
lang: zh-CN
permalink: pretty
excerpt_separator: "<!-- more -->"
paginate: 20
paginate_path: "/blog/page:num"
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- ".jekyll-cache"
- node_modules
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
author: 智宁居士
email: zhining@true-dhamma.com
logo: "/uploads/Dhamma_Wheel.svg.webp"
css_inline: true
favicons:
  '16': "/uploads/siteicon.png"
  '32': "/uploads/siteicon.png"
  '96': "/uploads/siteicon.png"
  '120': "/uploads/siteicon.png"
  '144': "/uploads/siteicon.png"
  '180': "/uploads/siteicon.png"
  '512': "/uploads/siteicon.png"
  '1024': "/uploads/siteicon.png"
navigation_header:
- title: 首页
  url: "/"
- title: 成瘾
  url: "/addiction/"
- title: 文章
  url: "/blog/"
- title: 巴利圣典
  url: "/tipitaka/"
- title: 网盘
  url: https://download.true-dhamma.com/
- title: 搜索&提问
  url: "/search/"
- title: 关于本站
  url: "/about/"
navigation_footer:
- title: Created by 智宁居士
  url: mailto:zhining@gmx.com
social_links:
  Twitter: 
  LinkedIn: 
  GitHub: 
  link: https://true-dhamma.github.io
  RSS: "/feed.xml"
sharing_links:
  Email: true
  universalshare: "#07C160
"
